name: Deploy Infrastructure

on:
  push
    #branches:
    #  - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
                                   # aws configuration.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform destroy 
      run: terraform destroy --auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    ##- name: Terraform Validate
     ##uses: hashicorp/terraform-github-actions/validate@v0.3.7
    # - name: Terraform Plan
    #   run: terraform plan
    #   env:
    #    GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
    #    TF_ACTION_WORKING_DIR: '.'
    #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      

    # - name: Terraform Apply
    #   run : terraform apply --auto-approve
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
    #     TF_ACTION_WORKING_DIR: '.'
    #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
